### ISSUE TITLE
Suspicious timeout value recommendation

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/ontap-tools-vmware-vsphere-912#3]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-912/configure/task_run_the_gos_timeout_scripts_for_windows.html

### Page title

Set timeout values for Windows guest operating systems

### Summary

> You can specify either a 60-second timeout or a 190-second timeout.

Is this correct? Not 180, not 90, but 190 seconds.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@scaleoutsean 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Thanks,
Jani

**Comment by netapp-jani** [comment]
@scaleoutsean , We checked this internally and the value 190 is correct. No changes made to the page.
